[tools]
node = "24"
lefthook = "latest"
rust = "latest"

[tasks.build]
description = "Build WASM"
run = """
wasm-pack build --no-pack --out-dir dist/esm --release

wasm-pack build --no-pack --out-dir dist/cjs --target nodejs --release
"""

[tasks.checks]
description = "Run all checks (formatting, linting)"
depends = ["format:check", "lint"]

[tasks.format]
description = "Format Rust code"
run = "cargo fmt"

[tasks."format:check"]
description = "Check Rust code formatting"
run = "cargo fmt --check"

[tasks.lint]
description = "Lint Rust code with Clippy"
run = "cargo clippy -- --deny warnings"
